# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # attempt to ignore shared-fvtt-bits, as per
  # https://github.com/dependabot/dependabot-core/issues/4364
  # see ticket https://github.com/n3dst4/gumshoe-fvtt/issues/904
  # attempt 2: move this block to the top and set schedule to same as the
  # second block
  # attempt 3: use "absolute" path to match the other block
  # next attempt will be to move it below the other block again
  - package-ecosystem: "npm"
    directory: "/packages/shared-fvtt-bits"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
