name: Regex Match
description: Match a input text with a input regex.
inputs:
  text:
    description: A text as the target for inputs.regex
    required: true
  regex:
    description: A regex for inputs.text. Supports capturing groups.
    required: true
  flags:
    description: Flags for inputs.regex, e.g. 'g', 'gm'
    required: false
outputs:
  match:
    description: The whole match. If inputs.regex doesn't match inputs.text, this value is "".
  group1:
    description: 1st capture group
  group2:
    description: 2nd capture group
  group3:
    description: 3rd capture group
  group4:
    description: 4th capture group
  group5:
    description: 5th capture group
  group6:
    description: 6th capture group
  group7:
    description: 7th capture group
  group8:
    description: 8th capture group
  group9:
    description: 9th capture group
runs:
  using: node16
  main: dist/index.js
