name: CI/CD

on:
  push

env:
  MANIFEST_FILE_NAME: "system.json"
  PUBLIC_PATH: "public"
  PACKAGE_FILE_NAME: "investigator.zip"
  PACKAGE_PATH: package
  DOWNLOAD_BASE: "https://github.com/${{github.repository}}/releases/download"

jobs:
  ci-cd:
    uses: ./.github/workflows/ci-cd-reusable.yml
    with:
      manifest_file_name: "system.json"
      public_path: "public"
      package_file_name: "investigator.zip"
  echo:
    uses: ./.github/workflows/echo-reusable.yml
    with:
      text: "Hello World!"
