name: CI/CD

on:
  push

env:
  MANIFEST_FILE_NAME: "system.json"
  PUBLIC_PATH: "public"
  PACKAGE_FILE_NAME: "investigator.zip"
  PACKAGE_PATH: package
  DOWNLOAD_BASE: "https://github.com/${{github.repository}}/releases/download"

jobs:
  ci-cd:
    # annoyingly, reusable workflows have to be in .github/workflows, either of
    # the local repo or a shared repo. There's literally no way of referencing
    # a reusable workflow in another folder, maing it impossible to use shared
    # workflows in subfolders (i.e. subrepos like we have.) Symlinks do not
    # work (GH does not follow them) so we are left referencing the
    # shared-fvtt-bits repo like this. See this discussion:
    # https://github.com/orgs/community/discussions/9050
    # Reusable workflows docs:
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows
    uses: n3dst4/shared-fvtt-bits/.github/workflows/ci-cd-reusable.yml@main
    permissions:
      contents: write
    with:
      manifest_file_name: "system.json"
      public_path: "public"
      package_file_name: "investigator.zip"

